name: Deploy and Generate

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
  schedule:
    - cron: "0 3 * * 6"
  workflow_dispatch:

jobs:
  deploy_and_generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Generate IP-ASN Rules
        run: python GenASNRules.py

      - name: Get Commit Message
        id: message
        uses: actions/github-script@v3
        env:
          FULL_COMMIT_MESSAGE: '${{ github.event.head_commit.message }}'
        with:
          result-encoding: string
          script: |
            var message = `${process.env.FULL_COMMIT_MESSAGE}`;
            core.info(message);
            if (message != '') return message;
            var time = new Date(Date.now()).toISOString();
            core.info(time);
            return `Generate at ${time}`;

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: generated
          publish_dir: ./generated
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          full_commit_message: ${{ steps.message.outputs.result }}
          force_orphan: true
